"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^%$jn89n#drcy8tx-*h2b+7$8ex%1a-dio5p+8m8rcc8+rf!9#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pylog',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

import logging
# logging.conf.dictCOnfiguration() method
LOGGING = {
    "version":1,
    "disable_existing_loggers":True,

    "formatters":{
        "simple":{
            "format":"%(asctime)s - %(levelname)s: %(message)s",
            "style":"%"
        },
        "file":{
            "format":"%(asctime)s - %(pathname)s - %(levelname)s - %(message)s",
            "style":"%"
        },
        "error":{
            "format":"{asctime} - {filename}/{module}/{funcName} at line - {lineno} {levelname} {message}",
            "style":"{"
        }
    },
    "filters":{
        "require_debug_true":{
            "()":"django.utils.log.RequireDebugTrue"
        },
        "require_debug_false":{
            "()":"django.utils.log.RequireDebugFalse"
        }
    },
    "handlers":{
        "console":{
            "level":"DEBUG",
            "class":"logging.StreamHandler",
            "formatter":"simple",
            "filters":["require_debug_true"]
        },
        "file":{
            "level":"DEBUG",
            "class":"logging.FileHandler",
            "filename":"logs/django.log",
            "formatter":"file",
            "filters":["require_debug_true"]
        },
        "rotating_file":{
            "level":"DEBUG",
            "class":"logging.handlers.RotatingFileHandler",
            "filename":"logs/rotating.log",
            "maxBytes":5*1024*1024,
            "backupCount":2,
            "formatter":"simple",
            "filters":["require_debug_true"]
        },
        "timed_rotating_file":{
            "level":"INFO",
            "class":"logging.handlers.TimedRotatingFileHandler",
            "filename":"logs/time_file.log",
            "when":"M",
            "interval":2,
            "backupCount":2,
            "formatter":"file",
            "filters":["require_debug_true"]
        },
        "request_file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": "logs/django_request.log",
            "formatter": "error",
            "filters": ["require_debug_true"]
        },
        "server_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": "logs/django_server.log",
            "formatter": "file",
            "filters": ["require_debug_true"]
        },
    },
    "loggers":{
        "mylogger":{
            "handlers":["timed_rotating_file"],
            "level":"ERROR",
            "propagate":True
        },
        "django":{
            "level":"DEBUG",
            "handlers":['rotating_file'],
            "propagate":True
        },
        "django.request":{
            "level":"ERROR",
            "handlers":['request_file'],
            "propagate":False
        },
        "django.server":{
            "level":"INFO",
            "handlers":['server_file'],
            "propagate":False
        },
    }
}

