# Generated by Django 3.0.6 on 2025-03-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadtos3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='img_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
