# Generated by Django 3.0.6 on 2025-03-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadtos3', '0002_auto_20250304_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='img_url',
            field=models.ImageField(upload_to='ststic/images/'),
        ),
    ]
