# Generated by Django 3.0.6 on 2025-03-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadtos3', '0003_auto_20250304_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='img_url',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
