# Generated by Django 3.0.6 on 2025-03-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadtos3', '0004_auto_20250304_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='img_url',
            field=models.URLField(),
        ),
    ]
