"""
Django settings for mwdemo project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'yg0&bwbond$1q%k#!r7u!9xm106ri51g28$1p-y10k8xd4j&zj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'mwapp',
]

MIDDLEWARE = [
    # custom middleware to capture errors
    'mwapp.middleware.logging.loggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mwdemo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mwdemo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': "django.db.backends.postgresql",
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

ADMINS = [
    ("parasuram", "parasuramech@gmail.com"),
]

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com" 
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "parasuramech@gmail.com"
EMAIL_HOST_PASSWORD = "zjlkwwxvjxxmybsb"
SERVER_EMAIL = EMAIL_HOST_USER

LOGGING = {
    "version":1,
    "disable_existing_loggers":True,
    "formatters":{
        "simple":{
            "format":"%(levelname)s - %(message)s",
            "style":"%"
        },
        "detailed":{
            "format":"%(asctime)s : %(levelname)s - %(message)s",
            "style":"%"
        }
    },
    "handlers":{
        "info_file":{
            "level":"INFO",
            "class":"logging.FileHandler",
            "filename":"logs/info.log",
            "formatter":"simple"
        },
        "error_file":{
            "level":"ERROR",
            "class":"logging.FileHandler",
            "filename":"logs/errors.log",
            "formatter":"detailed",
        },
        "db_file":{
            "level":"DEBUG",
            "class":"logging.FileHandler",
            "filename":"logs/db.log",
            "formatter":"simple",
        },
        "email_handler":{
            "level":"ERROR",
            "class":"django.utils.log.AdminEmailHandler",
            "include_html": True,
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'logging.handlers.SMTPHandler',
            'mailhost': ('smtp.gmail.com', 587),  
            'fromaddr': 'parasuramech@gmail.com',
            'toaddrs': ['parasuram.k@datayaan.com'], 
            'subject': 'Django Error Log',
            'credentials': ('parasuramech@gmail.com', 'zjlkwwxvjxxmybsb'),
            'secure': (),
            'timeout': 10.0,
        }
    },
    "loggers":{
        "mwapp.views":{
            "level":"INFO",
            "handlers":["error_file", "info_file",], # "mail_admins"],
            "propagate":True
        },
        "django.db.backends":{
            "level":"DEBUG",
            "handlers":['db_file'],
            "propagate":True

        }
    }
}
