# Generated by Django 3.0.6 on 2025-04-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mwapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserModel',
        ),
    ]
