# Generated by Django 3.0.6 on 2025-04-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mwapp', '0002_delete_customusermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
