# Generated by Django 3.0.6 on 2025-04-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20250403_1234'),
        ('auth', '0011_update_proxy_permissions'),
        ('mwapp', '0005_customusermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUserModel',
            new_name='user_details',
        ),
    ]
