# Generated by Django 3.0.6 on 2025-04-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mwapp', '0006_auto_20250403_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_details',
        ),
    ]
