# Generated by Django 3.0.6 on 2025-03-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consultant_charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_fees', models.CharField(blank=True, max_length=50, null=True)),
                ('out_patient', models.IntegerField(blank=True, null=True)),
                ('in_patient', models.IntegerField(blank=True, null=True)),
                ('daycare', models.IntegerField(blank=True, null=True)),
                ('MRP', models.IntegerField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab_charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=50, null=True)),
                ('out_patient', models.IntegerField(blank=True, null=True)),
                ('in_patient', models.IntegerField(blank=True, null=True)),
                ('daycare', models.IntegerField(blank=True, null=True)),
                ('MRP', models.IntegerField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_type', models.CharField(blank=True, max_length=50, null=True)),
                ('out_patient', models.IntegerField(blank=True, null=True)),
                ('in_patient', models.IntegerField(blank=True, null=True)),
                ('daycare', models.IntegerField(blank=True, null=True)),
                ('MRP', models.IntegerField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment_charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmet_name', models.CharField(blank=True, max_length=50, null=True)),
                ('out_patient', models.IntegerField(blank=True, null=True)),
                ('in_patient', models.IntegerField(blank=True, null=True)),
                ('daycare', models.IntegerField(blank=True, null=True)),
                ('MRP', models.IntegerField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
