# Generated by Django 3.0.6 on 2025-03-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment_charges',
            old_name='treatmet_name',
            new_name='treatment_name',
        ),
    ]
