# Generated by Django 3.0.6 on 2025-03-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20250317_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant_charges',
            old_name='Doctor_fees',
            new_name='Doctor_speciality',
        ),
        migrations.RenameField(
            model_name='consultant_charges',
            old_name='MRP',
            new_name='mrp',
        ),
        migrations.RenameField(
            model_name='lab_charges',
            old_name='MRP',
            new_name='mrp',
        ),
        migrations.RenameField(
            model_name='room_master',
            old_name='MRP',
            new_name='mrp',
        ),
        migrations.RenameField(
            model_name='treatment_charges',
            old_name='MRP',
            new_name='mrp',
        ),
    ]
