# Generated by Django 3.0.6 on 2025-03-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20250317_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant_charges',
            old_name='Doctor_speciality',
            new_name='doctor_speciality',
        ),
    ]
