# Generated by Django 3.0.6 on 2025-03-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_auto_20250317_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_master',
            old_name='Room_type',
            new_name='room_type',
        ),
    ]
