# Generated by Django 3.0.6 on 2025-03-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_auto_20250317_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='change_prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_plan', models.CharField(blank=True, max_length=20, null=True)),
                ('increase_by_amount', models.BooleanField(default=False)),
                ('decrease_by_amount', models.BooleanField(default=False)),
                ('increase_by_percentage', models.BooleanField(default=False)),
                ('decrease_by_percentage', models.BooleanField(default=False)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
