# Generated by Django 3.0.6 on 2025-03-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_change_prices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change_prices',
            old_name='value',
            new_name='amount',
        ),
    ]
