# Generated by Django 3.0.6 on 2025-03-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_auto_20250317_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='hosphital_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosphital_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('registered_date', models.DateTimeField()),
            ],
        ),
    ]
