# Generated by Django 3.0.6 on 2025-03-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_hosphital_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(blank=True, max_length=20, null=True)),
                ('field2', models.CharField(blank=True, max_length=20, null=True)),
                ('field3', models.CharField(blank=True, max_length=20, null=True)),
                ('field4', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
