# Generated by Django 3.0.6 on 2025-03-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_finance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='field1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='field2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='field3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='field4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
