# Generated by Django 3.0.6 on 2025-03-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_auto_20250319_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='speciality_master',
        ),
    ]
