# Generated by Django 3.0.6 on 2025-03-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='speciality_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('speciality_amount', models.IntegerField(blank=True, null=True)),
                ('speciality_currency', models.CharField(blank=True, max_length=50, null=True)),
                ('speciality_currency_symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('iu_id_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
